### ISSUE TITLE
Build system information

### ISSUE THREAD

**Issue by mmiddletonn** [imxieyi/iosu#2]
error: /Users/syndicate/Desktop/iosu-master/Pods/Target Support Files/Pods-iosu/Pods-iosu.debug.xcconfig: unable to open file (in target "iosu" in project "iosu") (in target 'iosu')

**Comment by imxieyi** [comment]
It is likely a CocoaPods issue. Please try reinstalling the latest version of CocoaPods and refer to the build environment on Travis CI:
[https://travis-ci.org/imxieyi/iosu](https://travis-ci.org/imxieyi/iosu)
